// Built-in Milkdrop sampler names that DON'T need an external texture file.
// Any sampler_<name> referenced in a .milk file that's not in this set is a
// custom texture and must be available under public/textures/.

const BUILT_IN_SAMPLERS = new Set<string>([
  // Framebuffer feedback — generated by Milkdrop at runtime
  "main",        // last comp-shader output (with warp)
  "fw_main",     // last frame as seen by warp shader
  "fc_main",     // last frame as seen by comp shader
  "pw_main",     // alt name in some versions
  "pc_main",
  // Blur pyramid — generated by Milkdrop
  "blur1",
  "blur2",
  "blur3",
  // Procedural noise — generated by Milkdrop
  "noise_lq",
  "noise_lq_lite",
  "noise_mq",
  "noise_hq",
  "noisevol_lq",
  "noisevol_hq",
]);

/** Extract custom (non-built-in) sampler names referenced by a .milk file. */
export function extractCustomSamplers(milkText: string): string[] {
  const matches = milkText.matchAll(/sampler_([a-zA-Z0-9_]+)/g);
  const found = new Set<string>();
  for (const m of matches) {
    const name = m[1];
    if (!BUILT_IN_SAMPLERS.has(name)) {
      found.add(name);
    }
  }
  return [...found].sort();
}

/** Resolve a custom sampler name to an actual file path under public/textures/.
 *  Tries a few extensions / casings since Milkdrop is permissive. */
export function findTextureFile(
  samplerName: string,
  availableFiles: ReadonlySet<string>,
): string | null {
  const exts = [".jpg", ".jpeg", ".png", ".bmp", ".tga", ".dds"];
  const lower = samplerName.toLowerCase();
  for (const f of availableFiles) {
    const stem = f.replace(/\.[^.]+$/, "");
    if (stem === samplerName || stem.toLowerCase() === lower) return f;
  }
  for (const ext of exts) {
    if (availableFiles.has(samplerName + ext)) return samplerName + ext;
    if (availableFiles.has(lower + ext)) return lower + ext;
  }
  return null;
}
